"""
Generate source_data CSVs for Fig 3, Fig 4 (already done by fig04_cnn_roc.py),
and Supplementary Fig S1, plus a README with SHA256 checksums.

Run from any directory; all paths are relative to this script's location.
"""

import csv
import hashlib
import datetime
from pathlib import Path

SCRIPT_DIR  = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent.parent   # DAD/
DATA_TSV    = (PROJECT_ROOT / "06_Report" / "Mr_Repro" /
               "external_validation" / "rcsb_seed" / "redocking_results.tsv")

# ── Load master TSV ───────────────────────────────────────────────────────────
rows = []
with open(DATA_TSV, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f, delimiter="\t")
    for row in reader:
        rows.append(row)

print(f"Loaded {len(rows)} rows from {DATA_TSV}")

# ── Fig 3 source data ─────────────────────────────────────────────────────────
fig3_fields = ["case_id", "family", "top_pose_rmsd_a", "best_pose_rmsd_a",
               "redock_pass", "best_pose_pass"]
fig3_path = SCRIPT_DIR / "fig03_source_data.csv"
with open(fig3_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fig3_fields, extrasaction="ignore")
    writer.writeheader()
    for r in rows:
        writer.writerow({k: r[k] for k in fig3_fields})
print(f"Written: {fig3_path}")

# ── Fig S1 source data ────────────────────────────────────────────────────────
figs1_fields = ["case_id", "best_pose_index", "redock_pass",
                "top_pose_rmsd_a", "best_pose_rmsd_a"]
figs1_path = SCRIPT_DIR / "figS01_source_data.csv"
with open(figs1_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=figs1_fields, extrasaction="ignore")
    writer.writeheader()
    for r in rows:
        writer.writerow({k: r[k] for k in figs1_fields})
print(f"Written: {figs1_path}")

# ── SHA256 checksums ──────────────────────────────────────────────────────────
def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

files_to_checksum = [
    ("fig03_source_data.csv",    fig3_path),
    ("fig04_source_data.csv",    SCRIPT_DIR / "fig04_source_data.csv"),
    ("fig04_metrics.csv",        SCRIPT_DIR / "fig04_metrics.csv"),
    ("figS01_source_data.csv",   figs1_path),
    ("redocking_results.tsv",    DATA_TSV),
]

checksums = {}
for label, path in files_to_checksum:
    if path.exists():
        checksums[label] = sha256(path)
    else:
        checksums[label] = "FILE_NOT_FOUND"

# ── README ────────────────────────────────────────────────────────────────────
readme_path = SCRIPT_DIR / "README.md"
now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

readme_lines = [
    "# Publication/figures/source_data/",
    "",
    "Nature-standard figure source data for DAD publication package.",
    f"Generated: {now}",
    "",
    "## Files",
    "",
    "| File | Figure | Content | Source TSV |",
    "|------|--------|---------|------------|",
    "| `fig03_source_data.csv` | Fig 3 | 16 cases × (case_id, family, top_pose_rmsd_a, best_pose_rmsd_a, redock_pass, best_pose_pass) | redocking_results.tsv |",
    "| `fig04_source_data.csv` | Fig 4 | 16 cases × (case_id, cnn_pose_score, top_pose_rmsd_a, best_pose_rmsd_a, redock_pass) | redocking_results.tsv |",
    "| `fig04_metrics.csv`     | Fig 4 | Computed metrics (Pearson r, AUROC, AUPRC, EF@25%, n) | Generated by fig04_cnn_roc.py |",
    "| `figS01_source_data.csv`| Fig S1 | 16 cases × (case_id, best_pose_index, redock_pass, top_pose_rmsd_a, best_pose_rmsd_a) | redocking_results.tsv |",
    "",
    "## Source TSV",
    "",
    f"All row data derives from:",
    f"  `06_Report/Mr_Repro/external_validation/rcsb_seed/redocking_results.tsv`",
    "",
    "## Generation scripts",
    "",
    "| Script | Generates |",
    "|--------|-----------|",
    "| `figures/source_data/generate_source_data.py` | fig03_source_data.csv, figS01_source_data.csv, this README |",
    "| `figures/source_code/fig04_cnn_roc.py` | fig04_source_data.csv, fig04_metrics.csv |",
    "",
    "## SHA256 checksums",
    "",
    "| File | SHA256 |",
    "|------|--------|",
]

for label, digest in checksums.items():
    readme_lines.append(f"| `{label}` | `{digest}` |")

readme_lines += [
    "",
    "## Notes",
    "",
    "- `fig04_metrics.csv` contains all metrics computed from data at runtime.",
    "  No metrics are hard-coded in the figure generation scripts.",
    "- `best_pose_index` in figS01_source_data.csv is 1-based (1 = CNN top rank).",
    "- `redock_pass` = PASS means top-pose RMSD ≤ 2.0 Å.",
    "- `best_pose_pass` = PASS means best-of-9 RMSD ≤ 2.0 Å (diagnostic metric only).",
]

with open(readme_path, "w", encoding="utf-8") as f:
    f.write("\n".join(readme_lines) + "\n")

print(f"Written: {readme_path}")
print("Done.")
